# Generated by Django 5.2.1 on 2025-05-30 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(
                        max_length=75, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        max_length=100, verbose_name="Short self-description of user."
                    ),
                ),
                (
                    "private",
                    models.BooleanField(
                        default=False,
                        verbose_name="Only followers can see this user's posts?",
                    ),
                ),
                (
                    "following",
                    models.ManyToManyField(
                        related_name="followers",
                        to="posts.user",
                        verbose_name="Users this user is following.",
                    ),
                ),
                (
                    "requested_followers",
                    models.ManyToManyField(
                        related_name="+",
                        to="posts.user",
                        verbose_name="Users with pending requests to follow this user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=280)),
                (
                    "datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Date and time this post was made.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.user",
                        verbose_name="Author of this post",
                    ),
                ),
            ],
        ),
    ]
